USE [master]
GO

/****** Object:  Database [Carrito]    Script Date: 13/06/2021 16:58:27 ******/
DROP DATABASE [Carrito]
GO

/****** Object:  Database [Carrito]    Script Date: 13/06/2021 16:58:27 ******/
CREATE DATABASE [Carrito]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Carrito', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Carrito.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Carrito_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Carrito_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Carrito].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Carrito] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Carrito] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Carrito] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Carrito] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Carrito] SET ARITHABORT OFF 
GO

ALTER DATABASE [Carrito] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Carrito] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Carrito] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Carrito] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Carrito] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Carrito] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Carrito] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Carrito] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Carrito] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Carrito] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Carrito] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Carrito] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Carrito] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Carrito] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Carrito] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Carrito] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Carrito] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Carrito] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Carrito] SET  MULTI_USER 
GO

ALTER DATABASE [Carrito] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Carrito] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Carrito] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Carrito] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Carrito] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Carrito] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Carrito] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Carrito] SET  READ_WRITE 
GO

